load("@rules_cc//cc:defs.bzl",  "cc_library")

cc_library(
    name = "maestro",
    srcs = ["MaestroDevice.cpp"],
    hdrs = ["MaestroDevice.hpp","DeviceOptions.hpp"],
    visibility = ["//visibility:public"],
)