load("@rules_cc//cc:defs.bzl",  "cc_library")


cc_library(
    name = "node",
    srcs = ["Node.cpp"],
    hdrs = ["Node.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "stack",
    srcs = ["Stack.cpp"],
    hdrs = ["Stack.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "linkedlist",
    srcs = ["LL.cpp"],
    hdrs = ["LL.hpp"],
    visibility = ["//visibility:public"],
)